version: 2
jobs: 
  build: 
    docker:
      - image: cimg/node:19.3.0-browsers
    steps: 
      - checkout
      - run: 
          command: |
              sudo npm install sfdx-cli --global
          name: "Install sfdx"
      - run:
          command: |
              sudo npm update --global sfdx-cli
              sfdx --version
              mkdir -p /tmp/artifacts/test_results
          name: "Update sfdx"
      - run: 
          command: |
              echo $SFDXURL_INTQA > /tmp/sfdx.url
              sfdx force:auth:sfdxurl:store -f /tmp/sfdx.url -a INTQA
              echo $SFDXURL_UATSTAGING > /tmp/sfdx.url
              sfdx force:auth:sfdxurl:store -f /tmp/sfdx.url -a UATSTAGING
              echo $SFDXURL_PROD > /tmp/sfdx.url
              sfdx force:auth:sfdxurl:store -f /tmp/sfdx.url -a PROD
          name: "Authenticate to Orgs"
      - run: 
          command: |
              #convert DX to legacy metadata
              sfdx force:source:convert -r force-app/main/default/ -d deploy
  
              cp -pr deploy /tmp/artifacts/deploy
              
              #update this to whatever the packaging branch should be!
              if [[ $CIRCLE_BRANCH == "main" ]];
              then 
                #deploy master branch to main org
                echo "CHECKONLY deploy $CIRCLE_BRANCH to main org ENABLED"
                ./dx-scripts/deploy.sh PROD checkonly
              elif [[ $CIRCLE_BRANCH == "intqa" ]];
              then
                #deploy INTQA branch to INTQA org
                echo "deploy $CIRCLE_BRANCH to INTQA org ENABLED"
                ./dx-scripts/deploy.sh INTQA
              elif [[ $CIRCLE_BRANCH == "uatstaging" ]];
              then
                #deploy UATSTAGING branch to UATSTAGING org
                echo "deploy $CIRCLE_BRANCH to UATSTAGING org ENABLED"
                ./dx-scripts/deploy.sh UATSTAGING
              else
                #deploy CHECKONLY to other branches
                echo "Not on Main Branch CHECKONLY - Deploy $CIRCLE_BRANCH to PROD org ENABLED"
                ./dx-scripts/deploy.sh PROD checkonly
              fi
          name: "Deploy To Permanent Branch/Orgs"
      # - store_artifacts: 
      #     destination: ./artifacts
      #     path: /tmp/artifacts
